### ISSUE TITLE
Namespace response variables

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-hubspot#3]
These variables should be `form.outcome` and `form.reason`:

https://github.com/activeprospect/leadconduit-integration-hubspot/blob/41bb478a71cb5f5dc6f6fb323459f1593d17e09f/src/form.coffee#L102-L103

These variables should be `contact.outcome` and `contact.reason`:

https://github.com/activeprospect/leadconduit-integration-hubspot/blob/41bb478a71cb5f5dc6f6fb323459f1593d17e09f/src/contact.coffee#L86-L87

**Comment by zalary** [comment]
resolved with PR #5
